url: "https://www.lsa-transports.com" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "/lsa" # the subpath of your site, e.g. /blog
title: "Lesaffre Service Assistance" # the name of your site, e.g. ACME Corp.

# Build settings
# permalink: :title/
sass:
  sass_dir: css

markdown: kramdown

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

title: Lesaffre Service Assistance | Taxi Montfort sur Meu, Yffendic, Monterfil
tagline: "Lesaffre Service Assistance | Taxi TPMR et Services pour Entreprises et scolaires"
description: "Lesaffre Service Assistance met à votre disposition des véhicules spacieux breaks, mini-car, mini-bus, pour transporter de 1 à 20 personnes?"
logo: /assets/images/logoLSA.png
